### ISSUE TITLE
One Logging Bridge per language

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/community#1970]
### Description

During the joint TC/GC call on Jan 11, we agreed on a few items we'd like to accomplish this year. One such item was creating at least one logging bridge per Language SIG, so that our end-users can start using OTLP Logging natively on their applications.

We'll strive to get at least one logging bridge for each supported language. Language SIGs will be free to decide which bridge to implement based on the needs of their audiences.

### Project Board

To be created.

### Deliverables

For each one of the following languages, there should be at least one logging bridge available, either as part of their core repository or as part of their contrib repository. Usage of such bridge should be documented on opentelemetry.io's website.

Languages (100% of the languages available when this issue was created):

- [x] https://github.com/open-telemetry/community/issues/1900
- [x] https://github.com/open-telemetry/community/issues/1901
- [x] https://github.com/open-telemetry/community/issues/1902
- [x] https://github.com/open-telemetry/community/issues/1903
- [x] https://github.com/open-telemetry/community/issues/1904
- [x] https://github.com/open-telemetry/community/issues/1905
- [x] https://github.com/open-telemetry/community/issues/1906
- [x] https://github.com/open-telemetry/community/issues/1907
- [ ] https://github.com/open-telemetry/opentelemetry-ruby/issues/1733
- [x] https://github.com/open-telemetry/community/issues/1909
- [x] https://github.com/open-telemetry/community/issues/1910

### Staffing / Help Wanted

We anticipate that Language SIG maintainers will share the vision that having at least one bridge, hopefully for the most used logging API for the language, is important for the SIG, and therefore, we don't anticipate new staffing requirements. However, we'll try to recruit new contributors to work on this once we have a few examples to follow.

#### Required staffing

@jpkrohling is the sponsor for this project and will work with the individual Language SIGs to implement this.

### Meeting Times

We'll use the regular Language SIGs meetings, as well as the maintainer's meeting on Monday.

### Timeline

We aim to complete this project by the end of 2024.

**Comment by jpkrohling** [comment]
Moved!

**Comment by jpkrohling** [comment]
I'm happy with this project's outcome: we ensured that ~all languages have a bridge available. Ruby is missing, and it might take some more time to get it done, given the current focus of the SIG. That said, I'm closing, as no more work is planned on this.
