### ISSUE TITLE
Create missing documents for projects

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/community#2088]
We have a few already running projects[^1] that do not have a document in the [projects](https://github.com/open-telemetry/community/tree/main/projects) folder, main reason is because they pre-date the process. Can the GC liaisons work with the SIGs to (a) verify if a document is required (i.e. the SIG is "not permanent") and if so create those documents?

- [x] Client Instrumentation SIG (can be copied from [this issue](https://github.com/open-telemetry/opentelemetry-specification/issues/2734) probably), @danielgblanco
- [x] Profiling SIG (can be copied from [this issue](https://github.com/open-telemetry/opentelemetry-specification/issues/2734) probably), @mtwo, @open-telemetry/profiling-maintainers 
- [x] System SemConv (can be copied from [this issue](https://github.com/open-telemetry/opentelemetry-specification/issues/3556) probably), @svrnm, @open-telemetry/semconv-system-approvers 
- [x] Prometheus Interoperability SIG, @alolita, @open-telemetry/wg-prometheus 
- [x] Agent Management SIG, @tedsuo, @open-telemetry/opamp-spec-approvers (probably not required to have one?)

Please check the box if either your SIG does not match the need to require a document or when you have added the document to the folder. 

[^1]: Picked them from https://github.com/orgs/open-telemetry/projects/29/views/1 during project triage session

**Comment by tigrannajaryan** [comment]
>Agent Management SIG

The SIG's work is actively in progress and there is no clear target when we can consider it "done". We can still add a project document if you prefer that. I don't have a strong opinion.

**Comment by dashpole** [comment]
I'll write the document for the prometheus compatibility WG.  I hope to wrap up the WG in the next few months.

**Comment by svrnm** [comment]
Thank you all!

> The SIG's work is actively in progress and there is no clear target when we can consider it "done". We can still add a project document if you prefer that. I don't have a strong opinion.

If the SIG is permanent (or very long running/with no clear end goal yet), I think we do not need a document.

**Comment by svrnm** [comment]
Since creating the document for the profiling SIG is probably as simple as copying [this issue](https://github.com/open-telemetry/opentelemetry-specification/issues/2734) into a markdown file, I argue it's still nice to have (same applies to the client instrumentation SIG, which has such an issue as well).

**Comment by danielgblanco** [comment]
Regarding the client-instrumentation SIG, there's in fact a single Project Document that was copied from the issue in https://github.com/open-telemetry/community/pull/1584 but the spec issue was not closed at the time. I just closed https://github.com/open-telemetry/opentelemetry-specification/issues/2734 with a comment.
